# This is a basic workflow to help you get started with Actions
name: Historical Volume Ingest

# Workflow will run every 15 minutes
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *' 
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setups up Python 3.10 and GitHub CLI
      - name: Install Dependencies
        env: # Or as an environment variable
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo $RELEASE_TOKEN > token.txt
          gh auth login --with-token < token.txt
          gh release download --pattern 'data.db.zip'
          pip install -r requirements.txt
          sudo apt install zip unzip -y
          unzip data.db.zip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Aggregates and Ingests Data into Redis
      - name: Volume Ingest
        env: # Or as an environment variable
          REDIS_HOST: ${{ secrets.REDIS_VOLUME_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_VOLUME_PORT }}
          REDIS_PW: ${{ secrets.REDIS_VOLUME_PW }}
        run: |
          python ./ingest.py