# This is a basic workflow to help you get started with Actions
name: Impute Historical Volume from Market Orders

# Workflow will run daily
on:
  schedule:
    - cron:  '0 5 * * *' 
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setups up Python 3.10 and GitHub CLI
      - name: Install Dependencies
        env: # Or as an environment variable
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo $RELEASE_TOKEN > token.txt
          gh auth login --with-token < token.txt
          gh release download --pattern 'data.db.zip'
          pip install -r requirements.txt
          sudo apt install zip unzip -y
          unzip data.db.zip
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # Downloads the latest database
      - name: Market Data Download
        run: |
          python ./app.py

      # Updates the release with the latest database          
      - name: Update SQLite Release
        env: # Or as an environment variable
          GH_USER: ${{ secrets.GH_USER }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
        run: |
          zip data.db.zip data.db
          export today=$(date +"%Y%m%d")
          git config --global user.email "${GH_EMAIL}"
          git config --global user.name "${GH_USER}"
          gh release create "v${today}" -n "SQLite3 Market Data ${today}" -t "Date: ${today}" data.db.zip