name: Precommit Hooks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
      - name: Install poetry
        run: python -m pip install poetry==2.0.1
      - name: Install Dependencies
        run: python -m poetry install
      - name: Run pre-commit
        run: python -m poetry run pre-commit run --all-files
